model_type: "hugging_face"
weights_name: null

imagenet_kwargs:
  transform_name: 'supervised_hugging_face'
  batch_size: 16

attack: 'pgd'

attack_kwargs:
  eps: 0.05
  norm: 'inf'
  max_iter: 10
  targeted: false

results_path: './results/l_inf/supervised/supervised_hugging_face'

