weights_name: 'moco_resnet50_linear-8xb32-steplr-100e_in1k_20220825-994c4128_torchvision'

imagenet_kwargs:
  transform_name: 'default'
  batch_size: 16

attack: 'pgd'

attack_kwargs:
  eps: 0.05
  norm: 'inf'
  max_iter: 10
  targeted: false

results_path: './results/l_inf/ssl/moco'