weights_name: 'simsiam_resnet50_linear-8xb512-coslr-90e_in1k_20220825-519b5135_torchvision'

imagenet_kwargs:
  transform_name: 'default'
  batch_size: 16

attack: 'pgd'

attack_kwargs:
  eps: 0.05
  norm: 'inf'
  max_iter: 10
  targeted: false

results_path: './results/l_inf/ssl/simsiam'