weights_name: 'swav_resnet50_linear-8xb32-coslr-100e_in1k_20220825-80341e08_torchvision'

imagenet_kwargs:
  transform_name: 'default'
  batch_size: 16

attack: 'pgd'

attack_kwargs:
  eps: 0.05
  norm: 'inf'
  max_iter: 10
  targeted: false

results_path: './results/l_inf/ssl/swav'