weights_name: 'simsiam_resnet50_linear-8xb512-coslr-90e_in1k_20220825-519b5135_torchvision'

imagenet_kwargs:
  transform_name: 'default'
  batch_size: 16

attack: 'pgd'

attack_kwargs:
  eps: 1.0
  norm: 2
  max_iter: 50
  targeted: false

results_path: './results/l2/ssl/simsiam'